import { formatScalar, formatScalarArray, formatString } from "./format.mjs";

const ASSET_BOUNDARY_NOTE = [
  "// Code-only Production Runtime: this module loads no asset of any origin —",
  "// no serialized geometry, no texture, no image, no sampled derivative, and no",
  "// encoded derivative of one.",
];

const THREE_NOTE = [
  "// `three` is injected into createObject3D rather than imported, so the",
  "// emitted runtime resolves no package of its own and stays executable in any",
  "// directory the build-time audit runs it from.",
];

function header(lines) {
  return ["// Generated by mesh-to-code. Do not edit by hand.", "//", ...lines];
}

function emitValue(value, indent) {
  const pad = " ".repeat(indent);
  if (typeof value === "number") return formatScalar(value);
  if (typeof value === "string") return formatString(value);
  if (typeof value === "boolean") return String(value);
  if (value === null) return "null";
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    if (value.every((item) => typeof item === "number")) {
      return formatScalarArray(value);
    }
    const items = value.map((item) => `${pad}  ${emitValue(item, indent + 2)}`);
    return `[\n${items.join(",\n")},\n${pad}]`;
  }
  const entries = Object.entries(value).map(
    ([key, child]) =>
      `${pad}  ${/^[A-Za-z_$][\w$]*$/.test(key) ? key : formatString(key)}: ${emitValue(
        child,
        indent + 2,
      )}`,
  );
  if (entries.length === 0) return "{}";
  return `{\n${entries.join(",\n")},\n${pad}}`;
}

export function emitRecipeLiteral(recipe) {
  return `Object.freeze(${emitValue(recipe, 0)})`;
}

export function emitRecipeModule(recipe) {
  return [
    ...header(ASSET_BOUNDARY_NOTE),
    "",
    `export const RECIPE = ${emitRecipeLiteral(recipe)};`,
    "",
    "export default RECIPE;",
    "",
  ].join("\n");
}

const OBJECT3D_ADAPTER = [
  "export function createObject3D(THREE, recipe = RECIPE) {",
  "  const root = new THREE.Group();",
  "  root.userData.semanticId = recipe.id;",
  "  for (const part of buildParts(recipe)) {",
  "    const geometry = new THREE.BufferGeometry();",
  '    geometry.setAttribute("position", new THREE.BufferAttribute(part.positions, 3));',
  "    geometry.setIndex(new THREE.BufferAttribute(part.indices, 1));",
  "    geometry.computeVertexNormals();",
  "    const mesh = new THREE.Mesh(",
  "      geometry,",
  "      new THREE.MeshStandardMaterial({",
  "        color: new THREE.Color(",
  "          part.material.color[0],",
  "          part.material.color[1],",
  "          part.material.color[2],",
  "        ),",
  "        roughness: part.material.roughness,",
  "        metalness: part.material.metalness,",
  "        flatShading: part.material.flatShading === true,",
  "      }),",
  "    );",
  "    mesh.userData.semanticId = part.semanticId;",
  "    root.add(mesh);",
  "  }",
  "  return root;",
  "}",
];

/**
 * Assemble the generator module.
 *
 * `builderSources` are the Contract Operator bodies the composition uses and
 * `assembleBody` wires them to the recipe. In `library` mode the recipe arrives
 * from its sibling module; in `inline` mode it is emitted into the same file, so
 * the result is one self-contained file with no import at all.
 */
export function emitGeneratorModule({
  builderSources,
  assembleBody,
  recipe,
  mode = "library",
}) {
  if (mode !== "library" && mode !== "inline") {
    throw new Error(`unknown emission mode: ${mode}`);
  }
  const preamble =
    mode === "library"
      ? ['import { RECIPE } from "./recipe.js";']
      : [`const RECIPE = ${emitRecipeLiteral(recipe)};`, "", "export { RECIPE };"];
  return [
    ...header([
      ...ASSET_BOUNDARY_NOTE,
      "//",
      ...THREE_NOTE,
      ...(mode === "inline"
        ? ["//", "// Inline mode: recipe and every operator this composition uses are", "// inlined here, and nothing it does not use is carried."]
        : []),
    ]),
    "",
    ...preamble,
    "",
    ...builderSources,
    "",
    "export function buildParts(recipe = RECIPE) {",
    assembleBody,
    "}",
    "",
    ...OBJECT3D_ADAPTER,
    "",
    "export default createObject3D;",
    "",
  ].join("\n");
}
