/**
 * Test fixtures are generated from code because the package must contain no
 * binary asset, no image, and no report. Every fixture here is a closed or
 * open triangle mesh written as Wavefront OBJ text, deterministic byte-for-byte
 * from its kind alone.
 */

const FIXTURE_KINDS = new Map([
  ["lathe-profile", latheProfileSolid],
  ["two-component", twoComponentSeparated],
  ["repeated-group", fiveInstanceRepeatedGroup],
  ["material-roles", distinctMaterialRoles],
  ["over-complex", overComplexInput],
  ["malformed-primitives", malformedPrimitives],
]);

export function listFixtureKinds() {
  return [...FIXTURE_KINDS.keys()];
}

export function generateFixtureObj(kind) {
  const builder = FIXTURE_KINDS.get(kind);
  if (!builder) {
    throw new Error(
      `unknown fixture kind: ${kind} (known: ${listFixtureKinds().join(", ")})`,
    );
  }
  return builder();
}

function formatNumber(value) {
  const rounded = Math.abs(value) < 1e-12 ? 0 : value;
  return rounded.toFixed(6);
}

function writeObj(groups, { extraLines = [] } = {}) {
  const lines = [
    "# generated by mesh-to-code fixtures; contains no authored artistic content",
  ];
  let vertexOffset = 0;
  for (const group of groups) {
    lines.push(`o ${group.name}`);
    for (let offset = 0; offset < group.positions.length; offset += 3) {
      lines.push(
        `v ${formatNumber(group.positions[offset])} ${formatNumber(
          group.positions[offset + 1],
        )} ${formatNumber(group.positions[offset + 2])}`,
      );
    }
    for (let face = 0; face < group.indices.length; face += 3) {
      lines.push(
        `f ${group.indices[face] + 1 + vertexOffset} ${
          group.indices[face + 1] + 1 + vertexOffset
        } ${group.indices[face + 2] + 1 + vertexOffset}`,
      );
    }
    vertexOffset += group.positions.length / 3;
  }
  lines.push(...extraLines);
  return `${lines.join("\n")}\n`;
}

/**
 * Revolve a profile — an array of [radius, height] samples — into a closed
 * solid with caps. This is the shape family the profile-lathe operator targets.
 */
export function revolveProfile({ profile, segments, name }) {
  const positions = [];
  const indices = [];
  const ringStart = [];

  for (const [radius, height] of profile) {
    ringStart.push(positions.length / 3);
    if (radius === 0) {
      positions.push(0, height, 0);
      continue;
    }
    for (let segment = 0; segment < segments; segment += 1) {
      const angle = (segment / segments) * Math.PI * 2;
      positions.push(Math.cos(angle) * radius, height, Math.sin(angle) * radius);
    }
  }

  for (let ring = 0; ring + 1 < profile.length; ring += 1) {
    const lowerRadius = profile[ring][0];
    const upperRadius = profile[ring + 1][0];
    const lower = ringStart[ring];
    const upper = ringStart[ring + 1];
    for (let segment = 0; segment < segments; segment += 1) {
      const next = (segment + 1) % segments;
      if (lowerRadius === 0) {
        indices.push(lower, upper + segment, upper + next);
      } else if (upperRadius === 0) {
        indices.push(lower + segment, lower + next, upper);
      } else {
        indices.push(lower + segment, lower + next, upper + next);
        indices.push(lower + segment, upper + next, upper + segment);
      }
    }
  }

  // Cap any non-zero-radius end ring so the fixture stays closed.
  for (const [ring, orientation] of [
    [0, -1],
    [profile.length - 1, 1],
  ]) {
    if (profile[ring][0] === 0) continue;
    const start = ringStart[ring];
    const centreIndex = positions.length / 3;
    positions.push(0, profile[ring][1], 0);
    for (let segment = 0; segment < segments; segment += 1) {
      const next = (segment + 1) % segments;
      if (orientation > 0) {
        indices.push(start + segment, start + next, centreIndex);
      } else {
        indices.push(start + next, start + segment, centreIndex);
      }
    }
  }

  return { name, positions, indices };
}

function latheProfileSolid() {
  return writeObj([
    revolveProfile({
      name: "lathe-profile-solid",
      segments: 32,
      profile: [
        [0.9, 0],
        [1.15, 0.35],
        [1.05, 0.9],
        [0.62, 1.6],
        [0.48, 2.2],
        [0.66, 2.62],
        [0.58, 2.9],
      ],
    }),
  ]);
}

function box({ name, centre, size }) {
  const [cx, cy, cz] = centre;
  const [sx, sy, sz] = size;
  const positions = [];
  for (const dz of [-0.5, 0.5]) {
    for (const dy of [-0.5, 0.5]) {
      for (const dx of [-0.5, 0.5]) {
        positions.push(cx + dx * sx, cy + dy * sy, cz + dz * sz);
      }
    }
  }
  const indices = [
    0, 2, 3, 0, 3, 1, 4, 5, 7, 4, 7, 6, 0, 1, 5, 0, 5, 4, 2, 6, 7, 2, 7, 3, 0, 4,
    6, 0, 6, 2, 1, 3, 7, 1, 7, 5,
  ];
  return { name, positions, indices };
}

function twoComponentSeparated() {
  return writeObj([
    box({ name: "component-a", centre: [-1.2, 0.5, 0], size: [1, 1, 1] }),
    box({ name: "component-b", centre: [1.4, 0.35, 0.2], size: [0.7, 0.7, 0.7] }),
  ]);
}

function fiveInstanceRepeatedGroup() {
  const placements = [
    [0, 0, 1],
    [1.7, 0.3, 0.82],
    [-1.55, -0.45, 0.94],
    [0.6, 1.85, 0.71],
    [-0.9, -1.7, 1.12],
  ];
  return writeObj(
    placements.map(([x, z, scale], index) => {
      const form = revolveProfile({
        name: `repeated-form-${index}`,
        segments: 12,
        profile: [
          [0.16 * scale, 0],
          [0.13 * scale, 0.55 * scale],
          [0.42 * scale, 0.72 * scale],
          [0.3 * scale, 0.95 * scale],
          [0, 1.02 * scale],
        ],
      });
      return {
        ...form,
        positions: form.positions.map((value, component) => {
          if (component % 3 === 0) return value + x;
          if (component % 3 === 2) return value + z;
          return value;
        }),
      };
    }),
  );
}

function distinctMaterialRoles() {
  // Material roles are carried as separate selectors, because OBJ material
  // libraries are external files and the package ships no asset.
  return writeObj([
    revolveProfile({
      name: "role-core",
      segments: 16,
      profile: [
        [0.35, 0],
        [0.3, 1.4],
        [0, 1.55],
      ],
    }),
    box({ name: "role-base", centre: [0, 0.08, 0], size: [1.1, 0.16, 1.1] }),
    box({ name: "role-accent", centre: [0, 1.0, 0.3], size: [0.18, 0.18, 0.18] }),
  ]);
}

function overComplexInput() {
  const groups = [];
  for (let index = 0; index < 24; index += 1) {
    groups.push(
      revolveProfile({
        name: `dense-part-${index}`,
        segments: 48,
        profile: [
          [0.2, 0],
          [0.34, 0.2],
          [0.26, 0.45],
          [0.31, 0.7],
          [0.18, 0.95],
          [0, 1.05],
        ].map(([radius, height]) => [radius, height + index * 0.02]),
      }),
    );
  }
  return writeObj(groups);
}

function malformedPrimitives() {
  return writeObj(
    [box({ name: "solid-part", centre: [0, 0.5, 0], size: [1, 1, 1] })],
    {
      extraLines: [
        "o line-strip",
        "v 2.000000 0.000000 0.000000",
        "v 2.000000 1.000000 0.000000",
        "l 9 10",
        "o point-cloud",
        "p 9",
      ],
    },
  );
}
